const services: { service: string; sName: string; price: string }[] = [
  { service: "Frontend", sName: "Figma bo`yicha moslashuvchan sahifa(1 bet)", price: "1 950 000 s0`m" },
  { service: "Frontend", sName: "Ko'p sahifali sayt (5 tagacha sahifa)", price: "3 900 000 so'm" },
  { service: "Frontend", sName: "Barcha brauzerlar uchun moslashtirish", price: "650 000 so'm" },
  { service: "Frontend", sName: "Interaktiv shakllar (tasdiqlash, step-by-step, email orqali yuborish)", price: "1 300 000 so'm" },
  { service: "Frontend", sName: "Sayt bo'yicha qidiruv / filtrlar / saralash", price: "1 300 000 so'm" },
  { service: "Frontend", sName: "Xaritalar (Google/Yandex), geolokatsiya", price: "560 000 so'm" },
  { service: "Frontend", sName: "Popup oynalar, modal oynalar, ogohlantirishlar", price: "380 000 so'm" },
  { service: "Frontend", sName: "Onlayn Yordamchi(Assistent)", price: "1 300 000 so'm" },

  { service: "Frontend", sName: "Bir betlik nusxa", price: "500 000 s0`m" },
  { service: "Frontend", sName: "Savat + buyurtmani rasmiylashtirish (checkout)", price: "2 600 000 so'm" },
  { service: "Frontend", sName: "Mijozning shaxsiy kabineti", price: "2 600 000 so'm" },
  { service: "Frontend", sName: "Payme / Click / Stripe orqali to'lov", price: "1 950 000 so'm" },
  { service: "Frontend", sName: "SEO optimallashtirish (meta-teglar, tezlik, Open Graph)", price: "560 000 so'm" },
  { service: "Frontend", sName: "Google Analytics / Yandex Metrika integratsiyasi", price: "780 000 so'm" },
  { service: "Frontend", sName: "Sitemap.xml, robots.txt sozlamalari", price: "320 000 so'm" },
  { service: "Frontend", sName: "Ko'p tilli saytga tarjima va sozlash", price: "1 300 000 so'm" },

  { service: "Frontend", sName: "Kesh, spamdan himoya, skriptlarni minimallashtirish", price: "1 040 000 so'm" },
  { service: "Frontend", sName: "Domen va hosting sozlamalari (Vercel, Render, VPS va h.k.)", price: "780 000 so'm" },
  { service: "Frontend", sName: "PageSpeed optimallashtirish, yuklash tezligini oshirish", price: "1 300 000 so'm" },
  
  { service: "Backend", sName: "Rest API ishlab chiqish", price: "1 950 000 so`m" },
  { service: "Backend", sName: "Malumotlar bazasini loyihalash (MySQL, PostgreSQL)", price: "1 300 000 so`m" },
  { service: "Backend", sName: "Bog`lanishlarni sozlash va optimallashtirish", price: "1 040 000 so`m" },
  { service: "Backend", sName: "GraphQL API ishlab chiqish", price: "2 600 000 so`m" },
  { service: "Backend", sName: "Ro`yhatdan o`tish, login, JWT yangilash tokenlari", price: "1 560 000 so`m" },
  { service: "Backend", sName: "Crud, foydalanuvchi rollari, filtrlar", price: "3 250 000 so`m" },
  { service: "Backend", sName: "Strapi / Sanity / Directus sozlash", price: "1 950 000 so`m" },
  { service: "Backend", sName: "Unit teslar, Postman, Swagger hujjatlari", price: "1 300 000 so`m" },
  { service: "Backend", sName: "CI/CD, GitHub Actions, monitoring", price: "1 300 000 so`m" },

  { service: "Dizayn", sName: "Landing sahifa (1 bet)", price: "1 500 000 so`m" },
  { service: "Dizayn", sName: "Ko'p sahifali sayt (5 tagacha sahifa)", price: "6 000 000 so`m" },
  { service: "Dizayn", sName: "Ilova uchun UI dizayn (5 tagacha ekran)", price: "4 250 000 so`m" },
  { service: "Dizayn", sName: "To'liq UX/UI to'plami (10–15 ekran)", price: "10 400 000 so'm" },
  { service: "Dizayn", sName: "Logotip yaratish", price: "1 300 000 so`m" },
  { service: "Dizayn", sName: "Brendbuk (PDF formatdagi qo'llanma)", price: "260 000 so`m" },
  { service: "Dizayn", sName: "Akkountni bezatish (avatar, cover va h.k.)", price: "650 000 so`m" },
  { service: "Dizayn", sName: "Amaldagi sayt dizaynini yangilash", price: "1 560 000 so`m" },
  { service: "Dizayn", sName: "Prototip (wireframe, foydalanuvchi yo'li)", price: "1 040 000 so`m" },

  { service: "Telegram Bot", sName: "Ro'yxat, menyu, shakllar, xabarnomalar bilan bot", price: "2 600 000 so`m" },
  { service: "Telegram Bot", sName: "Shaxsiy kabinet va admin panelga ega bot", price: "3 250 000 so`m" },
  { service: "Telegram Bot", sName: "Google Sheets / email / CRM bilan integratsiya", price: "1 950 000 so`m" },
  { service: "Telegram Bot", sName: "Avtoxabarlar, buyurtmalar, holatlar bilan bot", price: "2 600 000 so`m" },
  { service: "Telegram Bot", sName: "Xizmatlar, bron qilish, aloqa uchun ariza bot", price: "1 950 000 so`m" },
  { service: "Telegram Bot", sName: "Telegram ichida interaktiv ilova", price: "3 900 000 so`m" },
  { service: "Telegram Bot", sName: "Telegramda internet do'kon (katalog, to'lov, buyurtmalar)", price: "6 500 000 so`m" },
  { service: "Telegram Bot", sName: "Ma'lumotlar va mantiq bilan test/so'rovnoma", price: "3 250 000 so`m" },
  { service: "Telegram Bot", sName: "Foydalanuvchi ma'lumotlari bilan shaxsiy kabinet", price: "3 900 000 so`m" },
  { service: "Telegram Bot", sName: "Telegram ichida mini CRM (biznes / menejerlar uchun)", price: "5 200 000 so`m" },
  { service: "Telegram Bot", sName: "Telegram botga ChatGPT / AI API ni qo'shish", price: "3 250 000 so`m" },
];
